name: Docker image build test

on:
  pull_request:

jobs:
  docker:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      id: build-image
      run: |
        # Build docker image
        docker build .
        echo "Building image..."
