on:
  push:
    branches:
      - main
    paths:
      - ansible/**
      - src/**
      - .github/workflows/run-ansible.yml

jobs:
  ansible:
    name: "Run Ansible"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ansible
          key: ${{secrets.AWS_PEM_KEY}}
          options: |
            --inventory inventory.yml