name: "Terraform Plan"

# on:
#   pull_request:

on:
    push:
        branches:
        - BRUU-1142-test-deploy-from-github-to-aws-lambda-by-terraform

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    #   contents: read
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS Credentials OIDC
          uses: aws-actions/configure-aws-credentials@v1
          with:
            # role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ap-northeast-1
        - name: Initialise project and view terraform plan
          run: |
            cd infra
            terraform fmt
            terraform init
            terraform plan -out=tfplan
